### ISSUE TITLE
Improve `Data.unite_parser` to handle missing taxonomy labels 

### ISSUE THREAD

**Issue by CunliangGeng** [MycoAI/MycoAI#4]
Improve the function `Data.unite_parser` to handle the headers that only have `id`, e.g.

```
>KY106088
GTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTATAGAAAAAAATGGAAGGGCCATGCGCTTAATTGCGCGGGCCCTCTCTTAT
```

**Comment by luukromeijn** [comment]
What exactly would you like to see improved about it? Your data does not seem to be labelled, judging from the fasta header. If you specify `tax_parser=None` in your `Data` object initialization, there should be no error:
```
data = Data('your_sequences.fasta', tax_parser=None)
```
Otherwise, you can write your own parsing function and pass it in the `tax_parser` argument.

**Comment by CunliangGeng** [comment]
I see. I was thinking the `Data.unite_parser` can handle both the UNITE fasta header and the header without labels (e.g. `>KY106088`). But you're right, in this case, it would be better for me to create a custom parser function.

**Comment by luukromeijn** [comment]
Alright 👍.  I actually think you don't need a parser function as your data is unlabelled (`tax_parser=None` should be sufficient). The FASTA header (KY106088) should appear as 'id' column in the `Data` object and you should be able to run it through the different models. You could even train it with Masked Language Modeling. Only the classification training task will error as it depends on the target labels.
